### ISSUE TITLE
Oops! Seems like your phone can't handle the pressure :P

### ISSUE THREAD

**Issue by mmz211** [dc297/tensorflow-android-artistic-style-transfer#1]
When I run this program, it complained:
Oops! Seems like your phone can't handle the pressure :P
Is there instructions for hardware configuration?

By the way, your project has no license info.

**Comment by deepessh** [comment]
Hey, I am aware of the issue. Can you share the image you were trying to perform the style transfer operation on?

As far as license info is concerned, you may use the code in any form you want. Just make sure the you give proper credits. And include a link to this github repository.

**Comment by deepessh** [comment]
Hey this issue should be fixed in the latest version. Please check it out.

**Comment by mmz211** [comment]
It works! 
Excellent work! 

I'd like to learn tensor on Android, would you kindly recommend some useful website or book?

**Comment by deepessh** [comment]
Great!

Tensorflow on android is pretty straightforward, You may refer to the tensorflow android examples in the [Official Repository](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) to learn more.
